### ISSUE TITLE
serial output truncated to 20 bytes

### ISSUE THREAD

**Issue by arturl** [lancaster-university/microbit-dal#141] opened 2016-05-06 17:15 UTC
Calling  `uBit.serial.send` with a string longer than 20 characters only emit 20 characters.

**Comment by jamesadevine** [comment] 2016-05-09 12:21
@arturl This is by design. 

I'm unsure whether we should wrap this, or whether the users application should be responsible for wrapping this.

`uBit.serial.send` returns the number of bytes sent, if you give a string greater than the current buffer size, then it will truncate it down, and returns the number of bytes it actually sent.

Traditionally I think this is the approach most circular buffer implementations take.

However, this could be a place where our different modes could come into play... perhaps `SYNC_SLEEP` should block until **ALL** characters have been sent, not just the just the characters in the buffer.

Thoughts @arturl @finneyj ?

**Comment by pelikhan** [comment] 2016-05-09 20:49
My toughts is that we should be able to tell the runtime to send the entire buffer to avoid clients implementing their own logic to send chunks. Seems that the runtime has more knowledge/opportunities to handle this in a memory/perf efficient way.

**Comment by jamesadevine** [comment] 2016-05-10 17:03
@arturl I retract my earlier statement:

> this was by design

I believe `SYNC_SLEEP` and `SYNC_SPINWAIT` modes ***should have** completed transmission of all bytes before returning control to the user.

`ASYNC` should behave exactly as you describe.

Apologies for the confusion here, I have patched this bug and committed to master [3b587e1].

**Comment by arturl** [comment] 2016-05-10 17:37
Sounds good to me, thanks!

**Comment by pelikhan** [comment] 2016-05-10 17:45
Any chance to tag this release?

**Comment by jamesadevine** [comment] 2016-05-11 13:12
Hi @pelikhan, this is in `v2.0.0-rc3`.

**Closed** 2016-05-13 16:33 UTC
